name: typecaster
version: 1.0.0+1
publish_to: none
description: Simple and Unique code editor. Focus on the most important line.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  get: ^3.25.4
  stop_watch_timer: ^0.7.0
  intl: ^0.16.1
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  fonts: 
    - 
      family: FiraCode
      fonts: 
        - 
          asset: assets/fonts/FiraCode-Regular.ttf
        - 
          asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700
        - 
          asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - 
          asset: assets/fonts/FiraCode-Light.ttf
          weight: 300
        - 
          asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
  uses-material-design: true
