Map<String, List<int>> languageExtensions = {
  '':[0],
  'cpp': [3],
  'cc': [3],
  'cxx': [3],
  'c++': [3],
  'hpp': [3],
  'hh': [3],
  'h++': [3],
  'hxx': [3],
  'dart': [4],
  'c': [5],
  'h': [3, 5],
  'asm': [6],
  'md': [7],
  'py': [8],
  'ts': [9],
  'json': [10],
  'js': [11],
  'hs': [12],
  'yaml': [13],
  'yml': [13],
  'env': [14],
  'html': [15],
  'php': [16],
  'asp': [17],
  'svg': [18],
  'xml': [19],
};
