name: codecraft
version: 1.1.0
publish_to: none
description: Simple and Unique code editor. Focus on the most important line.
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  get: ^4.1.4
  stop_watch_timer: ^1.3.1
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  cupertino_icons: ^1.0.3
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  fonts: 
    - family: FiraCode
      fonts: 
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
  uses-material-design: true